name: Ejecutar satelite.py cada 10 minutos

on:
  schedule:
    - cron: "2,12,22,32,42,52 * * * *"  # Ejecutar cada 10 min
  workflow_dispatch:  # También podrás ejecutarlo manualmente

jobs:
  run-satelite:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Ejecutar script
        run: python satelite.py

      - name: Subir imágenes generadas
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add media/
          git commit -m "Actualización automática de imágenes satélite" || echo "Sin cambios"
          git push
